version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: assistance_bot
    command: ../start.sh
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    env_file:
      - ".env"

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: celery_worker
    command: ../start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ".env"

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: celery_beat
    command: ../start-celerybeat.sh
    volumes:
      - .:/app
    env_file:
      - ".env"
