"""Remove description colum from Todoes table

Revision ID: 87d8c8ec1b19
Revises: da331a1ab667
Create Date: 2023-07-23 19:09:33.681914+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87d8c8ec1b19"
down_revision = "da331a1ab667"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todoes", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todoes", sa.Column("description", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
